from django.urls import path

from ICP import testdb
from . import views

urlpatterns = [
    path('testdb/', testdb.testdb),
    path('AdminLogin/', views.AdminLogin.as_view()),
    path('StudentLogin/', views.StudentLogin.as_view()),
    path('StudentRegister/', views.StudentRegister.as_view()),
    path('TeacherLogin/', views.TeacherLogin.as_view()),
    path('TeacherRegister/', views.TeacherRegister.as_view()),
    path('getAllCourses/', views.getAllCourses.as_view()),
    path('getCourseList/', views.getCourseList.as_view()), # 得到所有
    path('SelectCourse/', views.SelectCourse.as_view()),
    path('GetCourseInfo/', views.GetCourseInfo.as_view()),
    path('StudentPassWordChange/', views.StudentPassWordChange.as_view()),
    path('TeacherPassWordChange/', views.TeacherPassWordChange.as_view()),
    path('AdminPassWordChange/', views.AdminPassWordChange.as_view()),
    path('GetStudentCourseList/', views.GetStudentCourseList.as_view()),
    path('DropCourse/', views.DropCourse.as_view()),
    path('GetTeacherCourseList/', views.GetTeacherCourseList.as_view()),
    path('BuildCourse/', views.BuildCourse.as_view()),
    path('ChangeCourse/', views.ChangeCourse.as_view()),
    path('CancelCourse/', views.CancelCourse.as_view()),
    path('GetCommentList/', views.GetCommentList.as_view()),
    path('CommentCourse/', views.CommentCourse.as_view()),
    path('DeleteComment/', views.DeleteComment.as_view()),
    path('TeacherAddHomework/', views.TeacherAddHomework.as_view()),
    path('StudentAddHomework/', views.StudentAddHomework.as_view()),
    path('TeacherDeleteHomework/', views.TeacherDeleteHomework.as_view()),
    path('StudentDeleteHomework/', views.StudentDeleteHomework.as_view()),
    path('TeacherChangeHomework/', views.TeacherChangeHomework.as_view()),
    path('StudentChangeHomework/', views.StudentChangeHomework.as_view()),
    path('StudentChangeHomeworkState/', views.StudentChangeHomeworkState.as_view()),
    path('TeacherHomeworkList/', views.TeacherHomeworkList.as_view()),
    path('StudentHomeworkList/', views.StudentHomeworkList.as_view()),
    path('GetMainList/', views.GetMainList.as_view()),
    path('BuildMain/', views.BuildMain.as_view()),
    path('GetSecondList/', views.GetSecondList.as_view()),
    path('BuildSecond/', views.BuildSecond.as_view()),
    path('DeleteMain/', views.DeleteMain.as_view()),
    path('DeleteSecond/', views.DeleteSecond.as_view()),
    path('GetStudentList/', views.GetStudentList.as_view()),
    path('GetTeacherList/', views.GetTeacherList.as_view()),
    path('GetStudentCourseNum/', views.GetStudentCourseNum.as_view()),
    path('GetStudentCommentNum/', views.GetStudentCommentNum.as_view()),
    path('GetStudentDiscussNum/', views.GetStudentDiscussNum.as_view()),
    path('GetTeacherCourseNum/', views.GetTeacherCourseNum.as_view()),
    path('GetTeacherDiscussNum/', views.GetTeacherDiscussNum.as_view()),
    path('GetDegree/', views.GetDegree.as_view()),
    path('GetMain/', views.GetMain.as_view()),
]
