# Generated by Django 4.2.5 on 2023-11-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="管理员账号",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="管理员名称")),
                ("password", models.CharField(max_length=128, verbose_name="管理员密码")),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="课程ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="课程名字")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=10,
                        verbose_name="课程评分",
                    ),
                ),
                (
                    "introduction",
                    models.CharField(max_length=1000, verbose_name="课程介绍"),
                ),
            ],
            options={
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="MainComment",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="主评论ID"
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="主评论标题")),
                ("time", models.CharField(max_length=100, verbose_name="主评论发表时间")),
                ("isTeacher", models.IntegerField(verbose_name="是否教师发帖")),
                ("content", models.CharField(max_length=1000, verbose_name="主评论内容")),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.admin",
                    ),
                ),
            ],
            options={
                "db_table": "mainComment",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="教师工号",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="教师姓名")),
                ("password", models.CharField(max_length=128, verbose_name="教师密码")),
            ],
            options={
                "db_table": "teacher",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学号",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="学生姓名")),
                ("password", models.CharField(max_length=128, verbose_name="学生密码")),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="students", to="backend.course"
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="SecondComment",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="次评论ID"
                    ),
                ),
                ("time", models.CharField(max_length=100, verbose_name="次评论发表时间")),
                ("isTeacher", models.IntegerField(verbose_name="是否教师发帖")),
                ("content", models.CharField(max_length=1000, verbose_name="次评论内容")),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.admin",
                    ),
                ),
                (
                    "mainComment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.maincomment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "secondComment",
            },
        ),
        migrations.AddField(
            model_name="maincomment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.student",
            ),
        ),
        migrations.AddField(
            model_name="maincomment",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.teacher",
            ),
        ),
        migrations.CreateModel(
            name="HomeWork",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="作业ID"
                    ),
                ),
                ("start", models.CharField(max_length=128, verbose_name="作业开始时间")),
                ("end", models.CharField(max_length=128, verbose_name="作业结束时间")),
                ("content", models.CharField(max_length=1000, verbose_name="作业内容")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "homework",
            },
        ),
        migrations.CreateModel(
            name="CourseEval",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="评价ID"
                    ),
                ),
                ("time", models.CharField(max_length=128, verbose_name="评价时间")),
                ("content", models.CharField(max_length=1000, verbose_name="评价内容")),
                ("score", models.IntegerField(default=5, verbose_name="课程评分")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
            ],
            options={
                "db_table": "courseEval",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.teacher",
            ),
        ),
    ]
