# Generated by Django 4.2.5 on 2023-11-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="isTeacher",
            field=models.IntegerField(default=1, verbose_name="是否教师布置"),
            preserve_default=False,
        ),
    ]
