# Generated by Django 4.2.5 on 2023-11-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_homework_isteacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="student",
        ),
        migrations.AddField(
            model_name="student",
            name="homeworks",
            field=models.ManyToManyField(
                related_name="students", to="backend.homework"
            ),
        ),
    ]
