# Generated by Django 4.2.5 on 2023-11-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_remove_homework_student_student_homeworks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="课程ID"
            ),
        ),
        migrations.AlterField(
            model_name="courseeval",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="评价ID"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="作业ID"
            ),
        ),
        migrations.AlterField(
            model_name="maincomment",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="主评论ID"
            ),
        ),
        migrations.AlterField(
            model_name="secondcomment",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="次评论ID"
            ),
        ),
    ]
