# Generated by Django 4.2.5 on 2023-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_course_id_alter_courseeval_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=5.0, max_digits=10, verbose_name="课程评分"
            ),
        ),
    ]
