# Generated by Django 4.2.5 on 2023-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_course_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="discussCnt",
            field=models.IntegerField(default=0, verbose_name="主次评论总数"),
        ),
        migrations.AddField(
            model_name="student",
            name="evalCnt",
            field=models.IntegerField(default=0, verbose_name="课程评价总数"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="courseCnt",
            field=models.IntegerField(default=0, verbose_name="开设课程数"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="discussCnt",
            field=models.IntegerField(default=0, verbose_name="主次评论总数"),
        ),
    ]
