# Generated by Django 4.2.5 on 2023-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0006_student_discusscnt_student_evalcnt_teacher_coursecnt_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="admin",
            index=models.Index(fields=["id"], name="admin_id_c0fa98_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["id"], name="course_id_1077aa_idx"),
        ),
        migrations.AddIndex(
            model_name="courseeval",
            index=models.Index(fields=["id"], name="courseEval_id_6be004_idx"),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(fields=["id"], name="homework_id_becc9b_idx"),
        ),
        migrations.AddIndex(
            model_name="maincomment",
            index=models.Index(fields=["id"], name="mainComment_id_b08745_idx"),
        ),
        migrations.AddIndex(
            model_name="secondcomment",
            index=models.Index(fields=["id"], name="secondComme_id_a26a35_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["id"], name="student_id_eaeec3_idx"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["id"], name="teacher_id_dcd44a_idx"),
        ),
    ]
