# Generated by Django 4.2.5 on 2023-11-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_remove_student_homeworks_homework_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="start",
        ),
        migrations.CreateModel(
            name="Student_homework",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("state", models.IntegerField(verbose_name="是否完成")),
                (
                    "hid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.homework",
                    ),
                ),
                (
                    "sid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_homework",
                "indexes": [
                    models.Index(fields=["id"], name="student_hom_id_3275d8_idx")
                ],
            },
        ),
    ]
