# Generated by Django 4.2.5 on 2023-12-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_remove_homework_start_student_homework"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher_second",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.secondcomment",
                    ),
                ),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_second",
                "indexes": [
                    models.Index(
                        fields=["tid", "secid"], name="teacher_sec_tid_id_5e3de4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Teacher_main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.maincomment",
                    ),
                ),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_main",
                "indexes": [
                    models.Index(
                        fields=["tid", "mid"], name="teacher_mai_tid_id_668a0f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="teacher_add_homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.homework",
                    ),
                ),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_add_homework",
                "indexes": [
                    models.Index(
                        fields=["hid", "tid"], name="teacher_add_hid_id_bd274d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Student_second",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.secondcomment",
                    ),
                ),
                (
                    "sid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_second",
                "indexes": [
                    models.Index(
                        fields=["sid", "secid"], name="student_sec_sid_id_dbfcaa_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Student_main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.maincomment",
                    ),
                ),
                (
                    "sid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_main",
                "indexes": [
                    models.Index(
                        fields=["sid", "mid"], name="student_mai_sid_id_8205aa_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="student_add_homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.homework",
                    ),
                ),
                (
                    "sid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_add_homework",
                "indexes": [
                    models.Index(
                        fields=["hid", "sid"], name="student_add_hid_id_eb5c72_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Admin_second",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.admin"
                    ),
                ),
                (
                    "secid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.secondcomment",
                    ),
                ),
            ],
            options={
                "db_table": "admin_second",
                "indexes": [
                    models.Index(
                        fields=["aid", "secid"], name="admin_secon_aid_id_684703_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Admin_main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.admin"
                    ),
                ),
                (
                    "mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.maincomment",
                    ),
                ),
            ],
            options={
                "db_table": "admin_main",
                "indexes": [
                    models.Index(
                        fields=["aid", "mid"], name="admin_main_aid_id_264d23_idx"
                    )
                ],
            },
        ),
    ]
